kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}-{{ .Values.deployEnv }}
data:
  .dockerconfigjson: {{ .Values.image.ghcrSecret }}