apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.deployEnv }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}-{{ .Values.deployEnv }}
    release: prometheus-stack
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}-{{ .Values.deployEnv }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: {{ .Values.metricsPort }}